# docker-compose.yml
services:
  mlops:
    build: .
    container_name: hotel-mlops
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
      - ./metrics:/app/metrics
    environment:
      - RETRAIN_ON_START=true
    restart: unless-stopped
